name: Lint React app

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f2000136@ds.study.iitm.ac.in
        run: echo "Hello, world!"
